### ISSUE TITLE
Map does not get properly copied to custom maps folder if built from my documents

### ISSUE THREAD

**Issue by General-101** [Project-Cartographer/H2-Toolkit-Launcher#6]
When map is packaged from 

"C:\Program Files (x86)\Microsoft Games\Halo 2 Map Editor\tags"

A map file gets placed in

"C:\Program Files (x86)\Microsoft Games\Halo 2 Map Editor\Maps"

If the copy to custom maps folder is enabled then this map will be copied to the Halo 2 custom map folder in my documents in 

"C:\Users\[USERNAME]\Documents\My Games\Halo 2\Maps"

A second location in my documents for tags can also be used. Maps files can be packaged in my documents from

"C:\Users\[USERNAME]\Documents\Halo 2\tags"

If it is done from here a map file will be built in 

"C:\Users\[USERNAME]\Documents\Halo 2\maps"

this map will not be moved to the custom maps folder.

**Comment by num0005** [comment]
Will look into this, shouldn't be too hard to fix.
